MapProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from MapProject import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('user/', include("user.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
  
    path('login/', views.login, name="login"),
 
]

map/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    username = models.CharField(max_length=50,unique=True)
    email = models.EmailField(max_length=254)
    user_img = models.ImageField(null=True,blank=True)
    phone = models.CharField(max_length=100)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User

class LoginForm(forms.Form):
    username = forms.CharField(label="username")
    password = forms.CharField(label="Parol")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'label-input100'})
        self.fields['password'].widget.attrs.update({'class': 'label-input100'})

MapProject/views.py
from django.shortcuts import render, redirect

def index(request):
    return render(request, "index.html")

map/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.shortcuts import render
from .forms import LoginForm

# Create your views here.
def login(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    return render(request, "login_page.html", context)

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'assets/img/kurshub_logo_logoman_Az-02.jpg' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

    <!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <!--===============================================================================================-->
    
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <!--===============================================================================================-->
    
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
        
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
        
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
    <!--===============================================================================================-->
</head>
<body>
    {% include "navbar.html"%}
    {% block body %}
    {% endblock %}


        <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    
    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!--===============================================================================================-->
    <script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
        <!--===============================================================================================-->
    <script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
        <!--===============================================================================================-->
    <script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <!--===============================================================================================-->
    <script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
        <!--===============================================================================================-->
    <script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
        <!--===============================================================================================-->
    <script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
        <!--===============================================================================================-->
    <script src="{% static 'login/js/main.js' %}"></script>
    
</body>
</html>

templates/login_page.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="limiter">
	<div class="container-login100" style="background-color: #008374">
		<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
			<form class="login100-form validate-form" method="POST">{% csrf_token %}
				<span class="login100-form-title p-b-49">
					Giriş et
				</span>

				<div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
					<span class="label-input100">Username</span>
					{{form.username|as_crispy_field}}
					<span class="focus-input100" data-symbol="&#xf206;"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate="Password is required">
					<span class="label-input100">Password</span>
					{{form.password|as_crispy_field}}
					<span class="focus-input100" data-symbol="&#xf190;"></span>
				</div>

				<div class="text-right p-t-8 p-b-31">
					<a href="#">
						Forgot password?
					</a>
				</div>

				<div class="container-login100-form-btn">
					<div class="wrap-login100-form-btn">
						<div class="login100-form-bgbtn"></div>
						<button class="login100-form-btn">
							Login
						</button>
					</div>
				</div>

				<div class="txt1 text-center p-t-54 p-b-20">
					<span>
						Or Sign Up Using
					</span>
				</div>

				<div class="flex-c-m">
					<a href="#" class="login100-social-item bg1">
						<i class="fa fa-facebook"></i>
					</a>

					<a href="#" class="login100-social-item bg2">
						<i class="fa fa-twitter"></i>
					</a>

					<a href="#" class="login100-social-item bg3">
						<i class="fa fa-google"></i>
					</a>
				</div>

				<div class="flex-col-c p-t-155">
					<span class="txt1 p-b-17">
						Or Sign Up Using
					</span>

					<a href="#" class="txt2">
						Sign Up
					</a>
				</div>
			</form>
		</div>
	</div>
</div>


<div id="dropDownSelect1"></div>

{% endblock %}

templates/navbar.html
{% load static %}

<!-- ======= Header ======= -->
<section id="topbar" class="topbar d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
        <div class="contact-info d-flex align-items-center">
            <i class="bi bi-envelope d-flex align-items-center"><a
                    href="mailto:contact@example.com">contact@example.com</a></i>
            <i class="bi bi-phone d-flex align-items-center ms-4"><span>+1 5589 55488 55</span></i>
        </div>
        <div class="social-links d-none d-md-flex align-items-center">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
        </div>
    </div>
</section><!-- End Top Bar -->

<header id="header" class="header d-flex align-items-center">

    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
        <a href="index.html" class="logo d-flex align-items-center">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="assets/img/logo.png" alt=""> -->
            <h1>Map Project<span>.</span></h1>
        </a>
        <nav id="navbar" class="navbar">
            <ul>
                <li><a href="#hero">Ana Səhifə</a></li>
                <li><a href="#about">Haqqımızda</a></li>
                <li><a href="#services">Xidmətlər</a></li>
                <li><a href="#portfolio">Portfolio</a></li>
                <li><a href="#team">Komandamız</a></li>
                <li><a href="{% url 'user:login' %}">Giriş</a></li>
                <li><a href="#contact">Əlaqə</a></li>
            </ul>
        </nav><!-- .navbar -->

        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
</header><!-- End Header -->
<!-- End Header -->